SocialMediaMVCwebApp/ViewModels/DashboardViewModel.cs
using SocialMediaMVCwebApp.Models;

namespace SocialMediaMVCwebApp.ViewModels
{
    public class DashboardViewModel
    {
        public List<Post> Posts { get;set; } 
    }
}

SocialMediaMVCwebApp/ViewModels/UserDetailsViewModel.cs
namespace SocialMediaMVCwebApp.ViewModels
{
    public class UserDetailsViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string GenderName { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Region { get; set; }
        public List<PostViewModel> UserPosts { get; set; } = new List<PostViewModel>();
    }

}

SocialMediaMVCwebApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using SocialMediaMVCwebApp.Data;
using SocialMediaMVCwebApp.Interfaces;
using SocialMediaMVCwebApp.Models;
using SocialMediaMVCwebApp.Repository;
using SocialMediaMVCwebApp.ViewModels;
using System.Security.Claims;

namespace SocialMediaMVCwebApp.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;
        private readonly IUserRepository _userRepository;
        public DashboardController(IDashboardRepository dashboardRepository, IUserRepository userRepository)
        {
            _dashboardRepository = dashboardRepository;
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Index()
        {
            List<Post> userPosts = await _dashboardRepository.GetAllUserPosts();
            userPosts.Reverse();

            DashboardViewModel model = new DashboardViewModel();
            {
                model.Posts = userPosts;
            }

            return View(model);
        }

        public async Task<IActionResult> UserDetails()
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                return NotFound();
            }

            var user = await _userRepository.GetById(userId);

            var userDetailViewModel = new UserDetailsViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                GenderName = user.Gender?.NameOfGender,
                Country = user.Address?.Country,
                Location = user.Address?.Location,
                Region = user.Address?.Region,
            };
            return View(userDetailViewModel);
        }

    }
}

SocialMediaMVCwebApp/Controllers/PostController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialMediaMVCwebApp.Data;
using SocialMediaMVCwebApp.Interfaces;
using SocialMediaMVCwebApp.Models;
using SocialMediaMVCwebApp.ViewModels;
using System.Security.Claims;

namespace SocialMediaMVCwebApp.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PostController(IPostRepository postRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _postRepository = postRepository;
            _photoService = photoService;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: 
        [Authorize]
        public async Task<IActionResult> Index(int? postCategoryId, string searchTitle)
        {
            // Fetch all posts from the repository
            IEnumerable<Post> posts = await _postRepository.GetAllPosts();

            // Fetch post categories for the filter dropdown
            IEnumerable<PostCategory> categories = await _postRepository.GetAllPostCategories();

            // Filter posts by category if a category is selected
            if (postCategoryId.HasValue)
            {
                posts = posts.Where(post => post.PostCategoryId == postCategoryId.Value);
            }

            // Filter posts by title if a search query is provided
            if (!string.IsNullOrEmpty(searchTitle))
            {
                posts = posts.Where(post => post.Title.Contains(searchTitle, StringComparison.OrdinalIgnoreCase));
            }

            // Map posts to PostViewModel
            IEnumerable<PostViewModel> postViewModels = posts.Select(post => MapToViewModel(post));

            // Create a view model to pass the posts and categories to the view
            var viewModel = new PostIndexViewModel
            {
                Posts = postViewModels,
                PostCategories = categories.Select(pc => new SelectListItem
                {
                    Value = pc.Id.ToString(),
                    Text = pc.NameOfPostCategory
                }).ToList(),
                SelectedPostCategoryId = postCategoryId,
                SearchTitle = searchTitle  // Pass the search query to the view model
            };

            return View(viewModel);
        }



        // GET: Detail
        public async Task<IActionResult> Detail(int id)
        {
            Post post = await _postRepository.GetById(id);
            if (post == null) return NotFound();

            var comments = await _postRepository.GetCommentsByPostId(id);

            PostViewModel postViewModel = new PostViewModel
            {
                Id = post.Id,
                Title = post.Title,
                PostText = post.PostText,
                Image = post.Image,
                PostCategoryName = post.PostCategory.NameOfPostCategory,
                Country = post.Address?.Country,
                Location = post.Address?.Location,
                Region = post.Address?.Region,
                AppUserId = post.AppUserId,
                Comments = comments.Select(c => new CommentViewModel
                {
                    Id = c.Id,
                    Text = c.Text,
                    UserName = c.AppUser.UserName,
                    CreatedAt = c.CreatedAt
                }).ToList()
            };

            return View(postViewModel);
        }

        // GET: Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            // Fetch post categories from the repository
            IEnumerable<PostCategory> categories = await _postRepository.GetAllPostCategories();

            // Set the AppUserId (assuming you have access to the user ID from the current user context)
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            CreatePostViewModel model = new CreatePostViewModel
            {
                AppUserId = userId,  // Set the AppUserId here
                PostCategories = categories.Select(pc => new SelectListItem
                {
                    Value = pc.Id.ToString(),
                    Text = pc.NameOfPostCategory
                }).ToList()
            };

            return View(model);
        }
        
        //TODO POST: Create => add check for image extension
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePostViewModel model)
        {
            if (ModelState.IsValid)
            {
                ImageUploadResult result = await _photoService.AddPhotoAsync(model.Image, 400, 600);

                // Create a new Post
                Post post = new Post
                {
                    Title = model.Title,
                    PostText = model.PostText,
                    Image = result.Url.ToString(),  // You may want to add file upload handling here
                    PostCategoryId = model.PostCategoryId,
                    AppUserId = model.AppUserId,
                    Address = new Address
                    {
                        Country = model.Country,
                        Location = model.Location,
                        Region = model.Region
                    }
                };

                // Add the post to the repository
                _postRepository.Add(post);

                return RedirectToAction("Index"); // Redirect to the list of posts after creating
            }

            // If validation failed, fetch the post categories again
            IEnumerable<PostCategory> categories = await _postRepository.GetAllPostCategories();
            model.PostCategories = categories.Select(pc => new SelectListItem
            {
                Value = pc.Id.ToString(),
                Text = pc.NameOfPostCategory
            }).ToList();

            return View(model);
        }

        // GET: Edit
        public async Task<IActionResult> Edit(int id)
        {
            
            // Fetch the post by its ID
            Post post = await _postRepository.GetById(id);
            if (post == null)
            {
                return NotFound();
            }

            // Check if the current user is the owner of the post
            var currentUserId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (post.AppUserId != currentUserId) // Prevent access to other users' posts
            {
                return Forbid(); // Or redirect to an error page
            }

            // Fetch post categories to populate the dropdown list
            IEnumerable<PostCategory> categories = await _postRepository.GetAllPostCategories();

            // Map the post data to the EditPostViewModel
            EditPostViewModel model = new EditPostViewModel
            {
                Id = post.Id,
                Title = post.Title,
                PostText = post.PostText,
                PostCategoryId = post.PostCategoryId,
                PostCategories = categories.Select(pc => new SelectListItem
                {
                    Value = pc.Id.ToString(),
                    Text = pc.NameOfPostCategory
                }).ToList(),
                Country = post.Address?.Country,
                Location = post.Address?.Location,
                Region = post.Address?.Region
            };

         

            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditPostViewModel model)
        {
            if (ModelState.IsValid)
            {
                string imageUrl = model.Image != null
                    ? (await _photoService.AddPhotoAsync(model.Image, 400, 600)).Url.ToString()
                    : null;  // Or set a default image URL if no image is uploaded.

                // Fetch the existing post to update
                Post post = await _postRepository.GetById(model.Id);
                if (post == null)
                {
                    return NotFound();
                }

                // Update the post properties
                post.Title = model.Title;
                post.PostText = model.PostText;
                if (!string.IsNullOrEmpty(imageUrl))
                {
                    post.Image = imageUrl;  // Update the image URL if a new image was uploaded
                }
                post.PostCategoryId = model.PostCategoryId;
                post.Address.Country = model.Country;
                post.Address.Location = model.Location;
                post.Address.Region = model.Region;

                // Update the post in the repository
                _postRepository.Update(post);
                _postRepository.Save();

                return RedirectToAction("Index");
            }

            // If validation failed, fetch the post categories again
            var categories = await _postRepository.GetAllPostCategories();
            model.PostCategories = categories.Select(pc => new SelectListItem
            {
                Value = pc.Id.ToString(),
                Text = pc.NameOfPostCategory
            }).ToList();

            return View(model);
        }

        // GET: /Post/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var post = await _postRepository.GetById(id);
            if (post == null) return NotFound();

            // Check if the current user is the owner of the post
            var currentUserId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

SocialMediaMVCwebApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialMediaMVCwebApp.Data;
using SocialMediaMVCwebApp.Interfaces;
using SocialMediaMVCwebApp.Models;
using SocialMediaMVCwebApp.ViewModels;

namespace SocialMediaMVCwebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IPostRepository _postRepository; // Inject post repository
        private readonly AppDbContext _context;

        public UserController(IUserRepository userRepository, IPostRepository postRepository, AppDbContext context)
        {
            _userRepository = userRepository;
            _postRepository = postRepository;
            _context = context;
        }

        [HttpGet("users")]
        public async Task<IActionResult> Index()
        {
            var users = await _userRepository.GetAllUsers(); // Get users with Gender and Address included
            var userViewModels = users.Select(u => new UsersViewModel
            {
                Id = u.Id,
                UserName = u.UserName,
                GenderName = u.Gender?.NameOfGender, // Assuming Gender has a 'Name' property
                Country = u.Address?.Country,  // Assuming Address has 'Country'
                Location = u.Address?.Location, // Assuming Address has 'Location'
                Region = u.Address?.Region   // Assuming Address has 'Region'
                
            }).ToList();

            return View(userViewModels);
        }

        [HttpGet("users/details/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            var user = await _userRepository.GetById(id);
            if (user == null)
            {
                return NotFound();
            }

            var userPosts = await _postRepository.GetPostsByUserId(id);

            var userDetailViewModel = new UserDetailsViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                GenderName = user.Gender?.NameOfGender,
                Country = user.Address?.Country,
                Location = user.Address?.Location,
                Region = user.Address?.Region,
                UserPosts = userPosts.Select(p => new PostViewModel
                {
                    Id = p.Id,
                    Title = p.Title,
                    PostText = p.PostText,
                    Image = p.Image,
                    PostCategoryId = p.PostCategoryId,
                    PostCategoryName = p.PostCategory?.NameOfPostCategory,
                    Country = p.Address?.Country,
                    Location = p.Address?.Location,
                    Region = p.Address?.Region,
                    AppUserId = p.AppUserId
                }).ToList()
            };

            return View(userDetailViewModel);
        }

        [HttpGet("users/edit/{id}")]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userRepository.GetById(id);
            if (user == null)
            {
                return NotFound();
            }

            var genders = await _userRepository.GetAllGenders(); // Fetch the list of genders from the database
            var editUserViewModel = new UserEditViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                GenderId = user.GenderId,
                Country = user.Address?.Country,
                Location = user.Address?.Location,
                Region = user.Address?.Region,
                GenderOptions = new SelectList(genders, "Id", "NameOfGender", user.GenderId)
            };

            return View(editUserViewModel);
        }

        // make validation check
        [HttpPost("users/edit/{id}")]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.GenderOptions = new SelectList(await _context.Genders.ToListAsync(), "Id", "NameOfGender", model.GenderId);
                return View(model);
            }

            AppUser user = await _userRepository.GetById(model.Id);
            if (user == null)
            {
                return NotFound();
            }

            user.UserName = model.UserName;
            user.GenderId = model.GenderId;
            user.Address = new Address
            {
                Country = model.Country,
                Location = model.Location,
                Region = model.Region
            };

            _userRepository.Update(user);
            _userRepository.Save();

            return RedirectToAction("Details", new { id = user.Id });
        }




    }
}

SocialMediaMVCwebApp/Views/Dashboard/Index.cshtml
@using SocialMediaMVCwebApp.ViewModels
@model DashboardViewModel

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Your Posts</h1>
            <p class="lead text-body-secondary">In this page you can manipulate you posts as well as edit your personal account</p>
            <p>
                <a class="btn btn-primary my-2" asp-controller="Post" asp-action="Create">Create a new Post</a>
                <a class="btn btn-secondary my-2" asp-controller="Dashboard" asp-action="UserDetails">My Profile</a>
            </p>
        </div>
    </div>
</section>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var post in Model.Posts)
            {
                <div class="col-md-4 mb-4">
                    <div class="card card_hovering_resize shadow-sm h-100">
                        <img class="bd-placeholder-img img-top" width="100%" height="225" src="@post.Image" alt="Alternate Text" style="object-fit: cover;" />
                        <div class="card-body">
                            <h5 class="card-title font-weight-bold mb-2">@post.Title</h5>

                            <!-- Category and Location Information -->
                            <div class="mt-3">

                                <div class="d-flex align-items-center">
                                    <i class="bi bi-geo-alt text-danger me-2"></i>
                                    @if (!(post.Address.Location is null && post.Address.Country is null && post.Address.Region is null))
                                    {
                                        <span class="text-muted"><strong>Location:</strong>@post.Address.Country @post.Address.Region @post.Address.Location</span>
                                    }

                                </div>
                            </div>

                            <!-- Action Buttons -->
                            <div class="d-flex justify-content-between align-items-center mt-4">
                                <div class="btn-group">
                                    @*<a href="@Url.Action("Details", "Post", new { id = post.Id })" class="btn btn-sm btn-primary">View</a>*@

                                    <a type="button" class="btn btn-sm btn-primary" asp-controller="Post" asp-action="Detail" asp-route-id="@post.Id">View</a>
                                    

                                </div>
                                <small class="text-muted">@post.PostCategory.NameOfPostCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }




        </div>
    </div>
</div>

SocialMediaMVCwebApp/Views/Dashboard/UserDetails.cshtml
@model SocialMediaMVCwebApp.ViewModels.UserDetailsViewModel

<div class="mt-5 d-flex justify-content-center">
    <div class="card shadow-sm border-0 w-50 bg-dark bg-gradient">
        <div class="card-header bg-success bg-gradient text-white text-center">
            <h2>Your Profile</h2>
        </div>
        <div class="card-body d-flex flex-column align-items-center text-center">
            <!-- Display user profile picture as a placeholder -->
            <img src="https://via.placeholder.com/150" alt="User Profile Image" class="rounded-circle mb-3" />

            <!-- Display user details -->
            <div class="text-start" style="width: 100%; max-width: 400px;">
                <p><strong>Username:</strong> @Model.UserName</p>
                <p><strong>Gender:</strong> @(Model.GenderName ?? "Not Specified")</p>
                <p>
                    <strong>Location:</strong>
                    @if (string.IsNullOrWhiteSpace(Model.Country) &&
                    string.IsNullOrWhiteSpace(Model.Region) &&
                    string.IsNullOrWhiteSpace(Model.Location))
                    {
                        <span>Not Specified</span>
                    }
                    else
                    {
                        <span>@Model.Location, @Model.Region, @Model.Country</span>
                    }
                </p>
            </div>
        </div>


        <div class="card-footer text-center">
            <a asp-controller="User" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit your Profile</a>

        </div>
    </div>
</div>